name: Deploy Node.js App to EC2
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ -d /home/ubuntu/my-app/.git ]; then
              cd /home/ubuntu/my-app
              git pull origin master
            else
              git clone https://github.com/rwirba1/tetst.git /home/ubuntu/my-app
              cd /home/ubuntu/my-app
            fi
            npm install
            pm2 restart all || pm2 start app.js --name my-app
